import Head from 'next/head'
import { useMemo } from 'react'
import { createAvatar } from '@dicebear/core'
import { lorelei } from '@dicebear/collection'

export default function Home() {
  const avatar = useMemo(() => {
    return createAvatar(lorelei, {
      size: 128,
      // ... other options
    }).toDataUriSync();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <img src={avatar} alt="Avatar" />
      </main>
    </>
  )
}
